language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
script:
  - xctool -project YandexTranslate.xcodeproj -sdk iphonesimulator -scheme YandexTranslate -configuration Debug
